name: DifficultyTweaks
version: '${project.version}'
main: me.unleqitq.difficultytweaks.DifficultyTweaks
api-version: 1.17
load: STARTUP
authors: [ UnleqitQ ]
libraries:
  - net.objecthunter:exp4j:0.4.8
